# Generated by Django 4.1.13 on 2026-04-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webiste', '0002_user_delete_accountform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webiste.user')),
            ],
            bases=('webiste.user',),
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('tipe_kategori', models.CharField(max_length=255)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='webiste.admin')),
            ],
        ),
        migrations.CreateModel(
            name='UserBiasa',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webiste.user')),
            ],
            bases=('webiste.user',),
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id_pengeluaran', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.FloatField()),
                ('tanggal', models.DateField()),
                ('deskripsi', models.CharField(max_length=255)),
                ('id_kategori', models.ForeignKey(db_column='id_kategori', on_delete=django.db.models.deletion.CASCADE, to='webiste.kategori')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='webiste.userbiasa')),
            ],
        ),
        migrations.CreateModel(
            name='Pemasukan',
            fields=[
                ('id_pemasukan', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.FloatField()),
                ('tanggal', models.DateField()),
                ('deskripsi', models.CharField(max_length=255)),
                ('id_kategori', models.ForeignKey(db_column='id_kategori', on_delete=django.db.models.deletion.CASCADE, to='webiste.kategori')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='webiste.userbiasa')),
            ],
        ),
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id_anggaran', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_anggaran', models.FloatField()),
                ('periode', models.CharField(max_length=255)),
                ('id_kategori', models.ForeignKey(db_column='id_kategori', on_delete=django.db.models.deletion.CASCADE, to='webiste.kategori')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='webiste.userbiasa')),
            ],
        ),
    ]
