# Generated by Django 6.0.4 on 2026-06-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiste', '0003_admin_kategori_userbiasa_pengeluaran_pemasukan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='webiste.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
